services:
  web:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - ./content:/app/content
    environment:
      - DOCKER_BUILD=true
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1

volumes:
  content:
