services:
  web:
    build: .
    ports:
      - '3333:3000'
    volumes:
      - ./content:/app/content
    environment:
      - DOCKER_BUILD=true
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
# volumes:
#   content:
